### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by OnePieceMan** [JetBrains/clearcase#2] opened 2019-08-02 07:22 UTC
Right-click menu cannot be displayed【ClearCase】item.

IntelliJ IDEA 2019.2 (Ultimate Edition)
Build #IU-192.5728.74, built on July 18, 2019
Licensed to jetbrains js
Subscription is active until November 27, 2019
Runtime version: 1.8.0_212-release-1586-b4 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 978M
Cores: 4
Registry: git.explicit.commit.renames.prohibit.multiple.calls=false
Non-Bundled Plugins: FindBugs-IDEA, JBClearcasePlugin, Lombook Plugin, cn.yiiguxing.plugin.translate, com.alibaba.p3c.smartfox, com.jetbrains.darkPurpleTheme, izhangzhihao.rainbow.brackets, MavenRunHelper

**Comment by dmitriysmirnovjb** [comment] 2019-08-02 11:47
Check if changing Project mapping to the explicit project path in Settings | Version control helps

**Comment by OnePieceMan** [comment] 2019-08-07 07:07
There is no error in setting

![idea-01](https://user-images.githubusercontent.com/45265465/62601797-d1b87a00-b924-11e9-9119-4cc131897f1b.jpg)
![idea-02](https://user-images.githubusercontent.com/45265465/62601799-d2511080-b924-11e9-9f1c-67e3aadacbcf.jpg)

**Comment by OnePieceMan** [comment] 2019-08-07 07:24
in TransparentVcs.java file
![idea-03](https://user-images.githubusercontent.com/45265465/62602881-54423900-b927-11e9-9fd5-ecc5dcfb64f9.jpg)
This code is not initialized to load!

**Comment by dmitriysmirnovjb** [comment] 2019-08-12 07:55
> There is no error in setting
That is correct - no errors are shown because the setup is correct - it should work.

There were changes on the platform side that causeth the <Project> mapping to stop working.
The issue is fixed on the platform-side in 2019.2.1

**Closed as completed by dmitriysmirnovjb** 2019-08-12 07:55 UTC
